FROM java:8-jdk-alpine

COPY SpringBootHelloWorld-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch SpringBootHelloWorld-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","SpringBootHelloWorld-0.0.1-SNAPSHOT.jar"]
